# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nurDG6Hjdy3CXalFTnZzo7QXzMHHLwWH
"""

import streamlit as st
from backend.chatbot import SafeChatbot

st.set_page_config(page_title='Secure LLM Chatbot', layout='centered')

st.title('🔒 Secure LLM Chatbot')
st.write('A demo chatbot that filters PII and hate/bias content before replying.')

if 'bot' not in st.session_state:
    st.session_state['bot'] = SafeChatbot()

bot: SafeChatbot = st.session_state['bot']

if 'conversation' not in st.session_state:
    st.session_state['conversation'] = []

with st.form('input_form', clear_on_submit=True):
    user_input = st.text_area('You:', height=120)
    submitted = st.form_submit_button('Send')

if submitted and use