# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nurDG6Hjdy3CXalFTnZzo7QXzMHHLwWH
"""

import pandas as pd
import re
import nltk
nltk.download('punkt')


def load_and_clean(entries_path: str, targets_path: str):
    """Load uploaded CSVs and join them (assumes parallel indexing)."""
    entries = pd.read_csv(entries_path)
    targets = pd.read_csv(targets_path)

    # Simple check
    if len(entries) != len(targets):
        print('Warning: entry/target length mismatch')

    df = pd.concat([entries, targets], axis=1)

    # Basic cleaning: lowercase, remove excessive whitespace
    df['text'] = df['text'].astype(str).str.strip().str.replace('\n', ' ')
    df['text'] = df['text'].str.replace(r"\s+", ' ', regex=True)

    return df


if __name__ == '__main__':
    df = load_and_clean('data/entries.csv', 'data/targets.csv')
    print(df.head())