# -*- coding: utf-8 -*-
"""train_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nurDG6Hjdy3CXalFTnZzo7QXzMHHLwWH
"""

"""Train a TF-IDF + LogisticRegression classifier for hate speech detection.
This script expects the user's uploaded CSVs in data/entries.csv and data/targets.csv
"""
import os
import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from backend.preprocess import load_and_clean

ARTIFACT_DIR = 'artifacts'


def train(entries_path='data/entries.csv', targets_path='data/targets.csv'):
    os.makedirs(ARTIFACT_DIR, exist_ok=True)
    df = load_and_clean(entries_path, targets_path)

    # Assume label column is named 'label' with 0 (non-hate) and 1 (hate)
    X = df['text'].fillna('')
    y = df['label'].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    vect = TfidfVectorizer(max_features=20000, ngram_range=(1,2))
    Xtr = vect.fit_transform(X_train)

    clf = LogisticRegression(max_iter=1000)
    clf.fit(Xtr, y_train)

    # Save artifacts
    joblib.dump(vect, os.path.join(ARTIFACT_DIR, 'tfidf_vectorizer.joblib'))
    joblib.dump(clf, os.path.join(ARTIFACT_DIR, 'clf.joblib'))

    # Evaluate
    Xte = vect.transform(X_test)
    ypred = clf.predict(Xte)
    print('Accuracy:', accuracy_score(y_test, ypred))
    print(classification_report(y_test, ypred))


if __name__ == '__main__':
    train()