# -*- coding: utf-8 -*-
"""logger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nurDG6Hjdy3CXalFTnZzo7QXzMHHLwWH
"""

import json
import os
from datetime import datetime

class ConversationLogger:
    def __init__(self, logfile='logs/conversations.jsonl'):
        os.makedirs(os.path.dirname(logfile), exist_ok=True)
        self.logfile = logfile

    def log(self, user_input, model_output, blocked: bool, reasons=None):
        entry = {
            'timestamp': datetime.utcnow().isoformat() + 'Z',
            'user_input': user_input,
            'model_output': model_output,
            'blocked': bool(blocked),
            'reasons': reasons or []
        }
        with open(self.logfile, 'a', encoding='utf-8') as f:
            f.write(json.dumps(entry) + '\n')


if __name__ == '__main__':
    logger = ConversationLogger()
    logger.log('hello', 'hi there', False, [])
