# -*- coding: utf-8 -*-
"""hate_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nurDG6Hjdy3CXalFTnZzo7QXzMHHLwWH
"""

import joblib
from transformers import AutoTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from typing import List

# This module wraps a scikit-learn model saved via joblib.
# Training script (train_classifier.py) saves two artifacts: tfidf_vectorizer.joblib and clf.joblib

ARTIFACT_VECT = 'artifacts/tfidf_vectorizer.joblib'
ARTIFACT_CLF = 'artifacts/clf.joblib'


class HateClassifier:
    def __init__(self, vect_path=ARTIFACT_VECT, clf_path=ARTIFACT_CLF):
        self.vect = joblib.load(vect_path)
        self.clf = joblib.load(clf_path)

    def predict_proba(self, texts: List[str]):
        X = self.vect.transform(texts)
        return self.clf.predict_proba(X)

    def predict(self, texts: List[str]):
        X = self.vect.transform(texts)
        return self.clf.predict(X)


if __name__ == '__main__':
    clf = HateClassifier()
    print(clf.predict(["I love everyone.", "I hate group X."]))
